# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
#        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest
#        pip install git+ssh://git@github.com/Somerset-NHS-FT-DS-Improvement/sfttoolbox.git
        pip install -r requirements-ci.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test with pytest
      run: |
        pytest -v
